# Generated by Django 5.0.1 on 2024-01-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_season_article_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
