# Generated by Django 5.0.1 on 2024-01-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
