# Generated by Django 5.0.1 on 2024-01-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
